name: GitHub Actions Demo
run-name: üëπ ${{ github.actor }} is testing out GitHub Actions üëπ

on: [push]

jobs:
  TestJob:
    runs-on: ubuntu-latest
    steps:
      - name: "Step 1 / Print"
        run: echo "üéâ The job was automatically triggered by a ${{ github.event_name }} event üéâ"
      
      - name: "Step 2 / Print"
        run: echo "üêß This job is now running on a ${{ runner.os }} server hoster by GitHub üêß"

      - name: "Step 3 / Print"
        run: echo "üîé The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }} üîé"

      - name: "Step 4 / Checkout"
        uses: actions/checkout@v4

      - name: "Step 5 / Print"
        run: echo "üí° The ${{ github.repository }} repository has been cloned to the runner üí°"

      - name: "Step 6 / Print"
        run: |
          echo "üñ•Ô∏è The workflow is now ready to test your code on the runner üñ•Ô∏è"
          echo "Scratch Org Username: some_username" >> $GITHUB_STEP_SUMMARY
          echo "Scratch Org Password: some_password" >> $GITHUB_STEP_SUMMARY
          echo "Scratch Org URL: some_url" >> $GITHUB_STEP_SUMMARY

      - name: "Step 7 / List files in the repository"
        run: |
          ls ${{ github.workspace }}

      - name: "Step 8 / Print"
        run: echo "üçè This job's status is ${{ job.status }}."